### ISSUE TITLE
All Requests Failing with 401 Unauthorized

### ISSUE THREAD

**Issue by BigThunderSR** [samrum/OnStarJS#255]
As of yesterday, all requests are failing with "401 - Unauthorized" for everyone. The official apps are still working, so does not seem like the API is down.

**Comment by nilathedragon** [comment]
Did you have to sign-in again in the official app or did it just work right away?

**Comment by almoney** [comment]
May need to request a API interface from GM.

**Comment by mattfox27** [comment]
I'm receiving this same error, logged into Instagram online and problem persists

**Comment by CamSoper** [comment]
@samrum is this project still active? Looks like OnStar changed something on their end.

**Comment by samrum** [comment]
I've been merging fixes from the community as they come up but I'm not really involved in maintaining API access anymore.

**Comment by glassbase** [comment]
My app logged me out too. New prompt in app about “new account security” and I noticed the sign in process to be different.

**Comment by FieryFlames** [comment]
My WIP Swift client is also facing this issue. I noticed the new sign in flow in myBrand a few weeks ago, they have switched to signing in via OAuth2 on the respective brand's website instead of directly in app. I had a feeling they would kill the method unofficial libraries are using because that flow has some glaring security issues (2fa afaict was done entirely client side, so using API directly bypassed it 😬). This is good for security but OnStarJS's authentication will need to be rewritten for this flow (make sure you store the refresh token or whatever they call it in the new flow, the old flow had a `idToken` that OnStarJS didn't use when it should've)

**Comment by Maliron** [comment]
Do we think they will be able to update the auth method, or does this mark the end of us being able to access the API?

**Comment by FieryFlames** [comment]
I would be surprised if this means the end of API access. Someone just needs to write the code to handle the new authentication

**Comment by Maliron** [comment]
I pulled a new image, and even tried making a new UUID, but I am getting "Request Failed with status 403 - Forbidden" when trying to send a command. Any ideas?

**Comment by jianyu-li** [comment]
> I pulled a new image, and even tried making a new UUID, but I am getting "Request Failed with status 403 - Forbidden" when trying to send a command. Any ideas?

The fix hasn't been pushed out yet

**Comment by Maliron** [comment]
BigThunderSR rolled it in to his onstar2mqtt, I meant to post this on that thread. My bad.

**Comment by mattfox27** [comment]
Thank you!!!! Works great!!!
